### ISSUE TITLE
Family name is Genoa instead of Gelasio

### ISSUE THREAD

**Issue by cmfwyp** [EbenSorkin/Gelasio#1]
The family name for the regular font is Genoa instead of Gelasio in `fontinfo.plist` and `Gelasio.glyphs`.

https://github.com/EbenSorkin/Gelasio/blob/7814ebe4b20f28c4a262d5338216544d04023fce/Gelasio.ufo/fontinfo.plist#L13-L14

https://github.com/EbenSorkin/Gelasio/blob/7814ebe4b20f28c4a262d5338216544d04023fce/Gelasio.glyphs#L28147-L28156

**Comment by davelab6** [comment]
I suggest to just delete the UFO, now we have glyphsLib it isn't important
to have non-real-ufo files floating around getting stale

**Comment by EbenSorkin** [comment]
I agree.
